ame: Build

on:
  # push:
  #   branches: [ "master" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: disable git eol translation
      run: git config --global core.autocrlf false
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Node js v18
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 'v18'

      # Run build
    - name: Install Rustup using win.rustup.rs
      run: |
        # Disable the download progress bar which can cause perf issues
        $ProgressPreference = "SilentlyContinue"
        Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
        .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=none
        del rustup-init.exe
      shell: powershell
    - name: Build
      run: |
        npm i
        npm run dev
        cd src-tauri
        cargo build -r
      shell: bash
    - name: Create release asset
      run: |
        7z a -r realmz-windows.zip src-tauri/target/release
      shell: bash
    - name: Upload A Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: windows
        path: realmz-windows.zip