name: Build

on:
  # push:
  #   branches: [ "master" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node js v18
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 'v18'
    - name: Install dependency
      run: |
        sudo apt install libwebkit2gtk-4.0-dev \
        build-essential \
        curl \
        wget \
        file \
        libssl-dev \
        libgtk-3-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev \
        p7zip-full \
        p7zip-rar
    - name: Build
      run: |
        npm i
        npm run dev
        cd src-tauri
        cargo build -r
    - name: packaging
      run: 7z a -r swordbattle-linux.zip src-tauri/target/release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: linux
        path: swordbattle-linux.zip